name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/bst-build:latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Build
        run: cmake -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release -S . -B ./build && cmake --build ./build -j4
      - name: Test
        working-directory: ./build
        run: ctest
      - name: Run lint
        continue-on-error: true
        run: cmake --build ./build --target cpplint